### ISSUE TITLE
Disabling DeadCodeSniff

### ISSUE THREAD

**Issue by tomasnorre** [martin-helmich/typo3-typoscript-lint#1]
Hi,

First I really like you work here, and I'm about to implement it as part of my Automated QA, Thanks. :+1: 

This is more a question that an issue, hope it's ok to address it here.

I want to allow comments in my TypoScript files, and therefor my tslint.yml looks like following: 

```
sniffs:
  - class: Indentation
    parameters:
      useSpaces: true
      indentPerLevel: 4
  - class: OperatorWhitespace
  - class: RepeatingRValue
  - class: DuplicateAssignment
  - class: NestingConsistency
``` 

So right now it's basically just a copy of you tslint.dist.yml which the - class: DeadCode removed.

But when running the linter, with this tslint.yml as -c (config file) input, it still complain about the DeadCode/Comments.. 

If I changes useSpaces or indentPerLevel it instantly changes the responses I get from linting.

Is there something logically i'm completely missing in this tool?
