### ISSUE TITLE
Indentation of globalVar

### ISSUE THREAD

**Issue by misterboe** [martin-helmich/typo3-typoscript-lint#66]
My Code and Identation looks like that: 

```
## Disable Cache when logged in BE
[globalVar = TSFE:beUserLogin > 0]
  config {
    no_cache = 1
    sendCacheHeaders = 0
    cache_period = 0
  }
[global]
```

But i get an warning that identation sould be 0

**Comment by martin-helmich** [comment]
That's the desired default behaviour. You can change it to your desired behaviour by supplying the `indentCondition` option to the `Indentation` sniff in the config file.

```yaml

  - class: Indentation
    parameters:
      indentConditions: true  # <-- Here!
```
