### ISSUE TITLE
PHP Warnings for str_repeat()

### ISSUE THREAD

**Issue by peterkraume** [martin-helmich/typo3-typoscript-lint#79]
```
str_repeat(): Second argument has to be greater than or equal to 0 in ./vendor/helmich/typo3-typoscript-lint/src/Linter/Sniff/IndentationSniff.php on line 68
```

PHP Version: 7.2
typo3-typoscript-lint: 2.0.1
CLI Command: `./vendor/bin/typoscript-lint --fail-on-warnings -c build/lint/tslint.yaml`

my configuration:
```
paths:
  - packages/my_sitepackage/Configuration/

filePatterns:
  - "*.typoscript"
  - "*.tsconfig"
  - "*.ts"

sniffs:
  - class: Indentation
    parameters:
      indentPerLevel: 2
      indentConditions: true
  - class: RepeatingRValue
    disabled: true
  - class: NestingConsistency
    disabled: true
```
